### ISSUE TITLE
Validation problem after patch

### ISSUE THREAD

**Issue by chomiczon** [TheGrandWazoo/freenas-proxmox#36] opened 2019-01-29 20:22 UTC
Great job :) but

after patch proxmox 5.3-5 to 5.3-8 validation in ZFS over iSCSI not working properly.
There is validation problem on all targets accept FreeNAS-API. "Add" button is inactive (LIO, Comstar etc)  

![obraz](https://user-images.githubusercontent.com/38671506/51936961-a9960e80-2409-11e9-97b8-86a12a8b8b28.png)

**Comment by chomiczon** [comment] 2019-01-30 18:34
Other providers work fine if they were configured before patching or configured manualy via storage.cfg.
The only bug is fields validation  on other ZFS over iSCSI providers. "Add" button is inactive. You can see it on attached screen.

**Comment by TheGrandWazoo** [comment] 2019-01-30 19:47
Yep, I saw that. I am working on the pvemanager.js to remedy this.

**Comment by TheGrandWazoo** [comment] 2019-01-31 20:43
Looks like the 'allowBlank' property is causing the issue in the FreeNAS fields. Also found out the the 'allowBlank' property is not bindable in extjs. I could override it but it seem to be a feature request coming or I need to create a setter. I don't see any dynamic 'allowBlank' in the original pvemanager.js code so I am currently playing around with some options.

**Comment by TheGrandWazoo** [comment] 2019-02-03 16:52
Ok. Let me upgrade to 5.3-8 in the lab and take a look. Hold on.

**Comment by TheGrandWazoo** [comment] 2019-02-04 19:43
OK, the issue is with the 'deleteEmpty' property of the FreeNAS password field. Looking at alternatives or if needed. Maybe trying to over-Engineer the checks of the fields.

**Comment by TheGrandWazoo** [comment] 2019-02-12 20:21
Closing. Problem seems to be fixed. No additional comments/issues since last patch.

**Closed by TheGrandWazoo** 2019-02-12 20:21 UTC
Labels: bug
