### ISSUE TITLE
Problem with jfrog artifactory

### ISSUE THREAD

**Issue by Brav-o** [TheGrandWazoo/freenas-proxmox#153] opened 2023-08-01 18:00 UTC
Hi,
I just saw that artifactory stopped you acconts.
Can you upload the 2 files for apt somewhere else ?

**Comment by Tradeforlife** [comment] 2023-08-11 06:23
How's it going with setting up the new repository? Or how can I manually install it from source?

**Comment by Tradeforlife** [comment] 2023-08-11 23:04
> New repo is coming soon. Hopefully today.
Great!! I built a new prox node and went to install the apt... whoops no go :) thanks for you work.. love it.

**Comment by TheGrandWazoo** [comment] 2023-08-13 03:30
Duplicate of #151

**Comment by TheGrandWazoo** [comment] 2023-08-16 12:56
New repos now available. #157

**Comment by TheGrandWazoo** [comment] 2023-08-19 14:54
Closing due to being resolved. See README.md for details on using the new repos.

**Closed by TheGrandWazoo** 2023-08-19 14:54 UTC
Labels: question
