### ISSUE TITLE
FreeNAS-11.2-U3 & PVE 5.4-5 working?

### ISSUE THREAD

**Issue by getcom** [TheGrandWazoo/freenas-proxmox#41] opened 2019-05-05 21:43 UTC
Hello all,

As I could read in the description, the plugin should work with PVE 5.3.

My Setup is following:
**FreeNAS-11.2-U3** server with multipath iSCSI over Dual Infiniband ConnectX-2 HCA (as it is a PCIe 2.0 card, it gives me a workload of round about 25 to 28 Gbit/s over 8 iperf windows. I think this is a good base for iSCSI instead of NFS. The ZFS pool has 8 mirrored VDEVs (8x2 SAS HDDs) and a mirrored ZLOG (PCIe SSDs), the server has 256GB RAM. iSCSI is new to me and also your plugin patch, so maybe I made a mistake somewhere. PVE is version 5.4-5 and has three cluster nodes.

Here is the iSCSI testing setup:
In FreeNAS => Sharing => Block (iSCSI):
Target Global Configuration: 
    Base Name = iqn.2019-05.[TLD.DOMAIN.HOST]
    ISNS Server = [NONE]
    Pool Available Space Threshold (%) = 75
Portals:
   Discovery Auth Method = NONE
   Discovery Auth Group = NONE
   IP Address = [SUBNET1 IP]
   Port = 3260
   IP Address = [SUBNET2 IP]
   Port = 3260
Initiators:
   Group ID = 1
   Initiators = ALL
   Authorized Networks = ALL
Authorized Access:
   Nothing changed or added.
Target:
   Target Name = test-target1
   Portal Group ID = 1
   Initiators Group ID = 1
   Auth Method = NONE
Extents:
   Extent Name = test-target1
   Extent Type = Device
   Device = [POOLNAME]/[ZVOLNAME] (20T)
   Available Space Threshold (%) = 75
   LUN RPM = SSD

The test-target1 is recognized by the PVE cluster nodes.
If I want to create a new VM, I have to create a ZFS over iSCSI device first in the storage section of PVE. This is no problem because it only creates the meta data entries.
If I create a new VM and select that previously created device I will get following error message:

cannot create '[POOLNAME]/[ZVOLNAME]/vm-100-disk-0': parent is not a filesystem
TASK ERROR: unable to create VM 100 - error with cfs lock 'storage-vm100-disk0': command '/usr/bin/ssh -o 'BatchMode=yes' -i /etc/pve/priv/zfs/XXX.XXX.XXX.XXX_id_rsa root@XXX.XXX.XXX.XXX zfs create -s -b 4k -V 52428800k [POOLNAME]/[ZVOLNAME]/vm-100-disk-0' failed: exit code 1

The parent is the zvol device which cannot be a dataset and which cannot be mounted by default.
The command which failed was executed over a SSH connection and is a shell command. Is that correct? As I read this plugin patch should use the API and not SSH? This is confusing to me.
The patch should contain a documentation with a little bit more information to get a clearer picture how it should work. At the moment it is not working as expected, I assume that this is related to the newer PVE version, but because of the basic documentation I could be mistaken.
Thank you for your work. It is exactly what I`m missing in Proxmox.

Best regards, Ralf

**Comment by raczkow** [comment] 2019-05-06 07:23
I can confirm that problem exists in my environment.
When I try to start VM, I've got:
```
iscsiadm: No session found.
cannot create 'tank/pve/vm-101-cloudinit': dataset already exists
TASK ERROR: error with cfs lock 'storage-vmpool': command '/usr/bin/ssh -o 'BatchMode=yes' -i /etc/pve/priv/zfs/10.0.254.101_id_rsa root@10.0.254.101 zfs create -b 4k -V 4096k tank/pve/vm-101-cloudinit' failed: exit code 1
```

**Comment by getcom** [comment] 2019-05-06 09:04
Now I changed my settings in Freenas and created a dataset in the ZFS pool.
In FreeNAS I created a new target iscsi-target0 below this dataset which I used for the storage entry in PVE (ID=iscsi-zfs).
After that I tested again and created a new VM. 
The result is, that the zvol will be created in the dataset with the name vm-100-disk-0 or in the second try the vm-100-disk-1, but ended with an error. The PVE task viewer output is following:

> Use of uninitialized value $target_id in numeric eq (==) at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 508.
> TASK ERROR: unable to create VM 100 - error with cfs lock 'storage-iscsi-zfs': Unable to find the target id for iscsi-target0 at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 149.

This are the syslog messages:

> May  6 10:44:19 pvecn1 pvedaemon[2944]: <root@pam> starting task UPID:pvecn1:00006AA6:002B7AF0:5CCFF3E3:qmcreate:100:root@pam:
> May  6 10:44:20 pvecn1 pvedaemon[27302]: FreeNAS::lun_command : create_lu(/dev/zvol/pool1/iSCSI/vm-100-disk-1)
> May  6 10:44:20 pvecn1 pvedaemon[27302]: FreeNAS::api_call : setup : sucessfull
> May  6 10:44:20 pvecn1 pvedaemon[27302]: FreeNAS::API::get_globalconfig : target_basename=iqn.2019-05.de.hotelscholz.freenas1
> May  6 10:44:20 pvecn1 pvedaemon[27302]: FreeNAS::api_call : setup : sucessfull
> May  6 10:44:20 pvecn1 pvedaemon[27302]: FreeNAS::API::get_target() : sucessfull
> May  6 10:44:20 pvecn1 pvedaemon[27302]: FreeNAS::api_call : setup : sucessfull
> May  6 10:44:20 pvecn1 pvedaemon[27302]: FreeNAS::API::get_target_to_extent() : sucessfull
> May  6 10:44:20 pvecn1 pvedaemon[27302]: Use of uninitialized value $target_id in numeric eq (==) at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 508.
> May  6 10:44:20 pvecn1 pvedaemon[27302]: FreeNAS::API::freenas_get_first_available_lunid : return 0
> May  6 10:44:20 pvecn1 pvedaemon[27302]: FreeNAS::api_call : setup : sucessfull
> May  6 10:44:20 pvecn1 pvedaemon[27302]: FreeNAS::API::get_target() : sucessfull
> May  6 10:44:20 pvecn1 pvedaemon[27302]: FreeNAS::api_call : setup : sucessfull
> May  6 10:44:20 pvecn1 pvedaemon[27302]: FreeNAS::API::get_globalconfig : target_basename=iqn.2019-05.de.hotelscholz.freenas1
> May  6 10:44:20 pvecn1 pvedaemon[27302]: FreeNAS::api_call : setup : sucessfull
> May  6 10:44:20 pvecn1 pvedaemon[27302]: FreeNAS::API::get_target() : sucessfull
> May  6 10:44:20 pvecn1 pvedaemon[27302]: FreeNAS::API::freenas_list_lu : sucessfull
> May  6 10:44:20 pvecn1 pvedaemon[27302]: FreeNAS::list_lu(/dev/zvol/pool1/iSCSI/vm-100-disk-1):name : lun not found
> May  6 10:44:20 pvecn1 pvedaemon[27302]: FreeNAS::api_call : setup : sucessfull
> May  6 10:44:20 pvecn1 pvedaemon[27302]: FreeNAS::API::get_globalconfig : target_basename=iqn.2019-05.de.hotelscholz.freenas1
> May  6 10:44:20 pvecn1 pvedaemon[27302]: FreeNAS::api_call : setup : sucessfull
> May  6 10:44:20 pvecn1 pvedaemon[27302]: FreeNAS::API::get_target() : sucessfull
> May  6 10:44:20 pvecn1 pvedaemon[27302]: VM 100 creating disks failed
> May  6 10:44:20 pvecn1 pvedaemon[27302]: unable to create VM 100 - error with cfs lock 'storage-iscsi-zfs': Unable to find the target id for iscsi-target0 at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 149.
> May  6 10:44:20 pvecn1 pvedaemon[2944]: <root@pam> end task UPID:pvecn1:00006AA6:002B7AF0:5CCFF3E3:qmcreate:100:root@pam: unable to create VM 100 - error with cfs lock 'storage-iscsi-zfs': Unable to find the target id for iscsi-target0 at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 149.
> 

This are two problems: First is that it does not find the target ID for iscsi-target0, which I created in FreeNAS and used in PVE for the storage entry, and second is that it does not find the lun name for the new zvol.

**Comment by TheGrandWazoo** [comment] 2019-05-06 18:17
Good day.

First, I have NOT updated to 5.4-5 of Proxmox but I am at 5.4-3 and FreeNAS 11.2-U3.
Second, I do NOT run multipath iSCSI so I am not totally up on the technology but understand what it is trying to do. I use LACP for redundant connections instead of multipath.
Third, the plugin does use the API's but the backend Proxmox libs still uses some SSHing to do some of the tasks it needs. I currently have a development going on to make try to push as much as possible to the plugin...but there are 4 other "built-in" plugins that would suffer from this so I am trying not to break to much.

I will need to upgrade to 5.3-5 in my lab and see if the patches work or is some changes need to be made.

**Comment by getcom** [comment] 2019-05-06 19:16
Hello,

as I know there is no way in FreeBSD/FreeNAS to use LACP, Round Robin or anything similar with Infiniband HCAs. The only way is multipath which is very easy to setup. 
Thank you for your effort.

**Comment by TheGrandWazoo** [comment] 2019-05-07 14:20
Hi,

Yeah I saw that and do NOT (I believe) have any Infiniband controllers. I have cables for Network Switches to cascade for a stack. I was just letting you know how I test.

I am gong to update the patch set to 5.3-5 just to be up-to-date.

Will keep ticket open for a while until I verify my Infiniband inventory.

Thanks.

**Comment by getcom** [comment] 2019-05-07 20:08
Hi, 

just for information: 
To reduce the effort for you I first disabled multipath on the Infiniband HCAs and after that I used two Intel X710 cards with LACP and a different subnet for the Portal on FreeNAS and the Proxmox cluster nodes.
Both tests ended with the same results, same errors:

error with cfs lock 'storage-iSCSI-ZFS': Unable to find the target id for iscsi-target0 at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 149. 

What is the target id in Proxmox speech? Is it the ID which is used in the local database?
What is Proxmox doing here? It creates a zvol with the name vm-100-disk-n but asks for the target id of the initial zvol which is necessary to get a ZFV over iSCSI storage available for a new VM?

**Comment by getcom** [comment] 2019-05-07 22:57
Hello,

I found an additional problem:
If I want to delete a previously created zvol in Proxmox, I get following error:

Could not find lu_name for zvol vm-100-disk-1 at /usr/share/perl5/PVE/Storage/ZFSPlugin.pm line 116. (500)

**Comment by raczkow** [comment] 2019-05-08 16:24
My problems have been solved by today's updates.
@getcom - try to update your system and try again.

**Comment by TheGrandWazoo** [comment] 2019-05-08 17:07
@raczkow Was this the FreeNAS update 11.2-U4 or a Proxmox update?

**Comment by raczkow** [comment] 2019-05-08 17:08
Proxmox update. FreeNAS is still at 11.2-U3. I'll update to U4 at night.

**Comment by TheGrandWazoo** [comment] 2019-05-08 17:10
@raczkow Thank you. I am looking at the "ChangeLog" to see what they fixed.

**Comment by getcom** [comment] 2019-05-08 17:11
@raczkow 
**FreeNAS version:**
base-os-11.2-U3-c1844ecade4cafab1f7478b278eef7b9
freebsd-pkgdb-11.2-U3-c1844ecade4cafab1f7478b278eef7b9
freenas-pkg-tools-11.2-U3-c1844ecade4cafab1f7478b278eef7b9
FreeNASUI-11.2-U3-c1844ecade4cafab1f7478b278eef7b9
**PVE version:**
root@pvecn1:~/freenas-proxmox# pveversion --verbose
proxmox-ve: 5.4-1 (running kernel: 4.15.18-14-pve)
pve-manager: 5.4-5 (running version: 5.4-5/c6fdb264)
pve-kernel-4.15: 5.4-2
pve-kernel-4.15.18-14-pve: 4.15.18-38
pve-kernel-4.15.18-13-pve: 4.15.18-37
pve-kernel-4.15.18-12-pve: 4.15.18-36
corosync: 2.4.4-pve1
criu: 2.11.1-1~bpo90
glusterfs-client: 3.8.8-1
ksm-control-daemon: 1.2-2
libjs-extjs: 6.0.1-2
libpve-access-control: 5.1-9
libpve-apiclient-perl: 2.0-5
libpve-common-perl: 5.0-51
libpve-guest-common-perl: 2.0-20
libpve-http-server-perl: 2.0-13
libpve-storage-perl: 5.0-42
libqb0: 1.0.3-1~bpo9
lvm2: 2.02.168-pve6
lxc-pve: 3.1.0-3
lxcfs: 3.0.3-pve1
novnc-pve: 1.0.0-3
proxmox-widget-toolkit: 1.0-26
pve-cluster: 5.0-37
pve-container: 2.0-37
pve-docs: 5.4-2
pve-edk2-firmware: 1.20190312-1
pve-firewall: 3.0-20
pve-firmware: 2.0-6
pve-ha-manager: 2.0-9
pve-i18n: 1.1-4
pve-libspice-server1: 0.14.1-2
pve-qemu-kvm: 3.0.1-2
pve-xtermjs: 3.12.0-1
qemu-server: 5.0-51
smartmontools: 6.5+svn4324-1
spiceterm: 3.0-5
vncterm: 1.5-3
zfsutils-linux: 0.7.13-pve1~bpo2

**freenas-proxmox:**
root@pvecn1:~/freenas-proxmox# git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

I cannot see any update, neither for FreeNAS or this repo nor for Proxmox:

Are you talking about a PVE subscription update? I don`t have one because I`m working on a PoC.

**Comment by TheGrandWazoo** [comment] 2019-05-08 17:14
@raczkow I was talking about Proxmox VE not the FreeNAS add-in.  I have not updated that yet. Just want to know what changed.

**Comment by raczkow** [comment] 2019-05-08 17:21
I use no-subscription repos.

Here's my /var/log/apt/history.log:

After that, I've got problems with live migrating and running VMs:
```
Start-Date: 2019-05-06  09:05:52
Commandline: apt upgrade
Requested-By: raku (1000)
Install: pve-kernel-4.15.18-13-pve:amd64 (4.15.18-37, automatic)
Upgrade: proxmox-widget-toolkit:amd64 (1.0-25, 1.0-26), postfix:amd64 (3.1.9-0+deb9u2, 3.1.12-0+deb9u1), linux-libc-dev:amd64 (4.9.144-3.1, 4.9.168-1), postfix-sqlite:amd64 (3.1.9-0+deb9u2, 3.1.12-0+deb9u1), libjs-jquery:amd64 (3.1.1-2, 3.1.1-2+deb9u1), pve-firewall:amd64 (3.0-19, 3.0-20), pve-kernel-4.15.18-12-pve:amd64 (4.15.18-35, 4.15.18-36), pve-manager:amd64 (5.4-3, 5.4-5), libpve-common-perl:amd64 (5.0-50, 5.0-51), unzip:amd64 (6.0-21, 6.0-21+deb9u1), rsync:amd64 (3.1.2-1+deb9u1, 3.1.2-1+deb9u2), pve-kernel-4.15:amd64 (5.3-3, 5.4-1), base-files:amd64 (9.9+deb9u8, 9.9+deb9u9), libpng16-16:amd64 (1.6.28-1, 1.6.28-1+deb9u1)
End-Date: 2019-05-06  09:08:22
```
 
This is today's update when everything works OK:
```
Start-Date: 2019-05-08  18:16:28
Commandline: apt upgrade
Requested-By: raku (1000)
Install: pve-kernel-4.15.18-14-pve:amd64 (4.15.18-38, automatic)
Upgrade: libpve-access-control:amd64 (5.1-8, 5.1-9), libpve-storage-perl:amd64 (5.0-41, 5.0-42), pve-qemu-kvm:amd64 (2.12.1-3, 3.0.1-2), pve-cluster:amd64 (5.0-36, 5.0-37), qemu-server:amd64 (5.0-50, 5.0-51), pve-kernel-4.15:amd64 (5.4-1, 5.4-2)
End-Date: 2019-05-08  18:17:45
```

I don't know, what could go wrong with update from 2019-05-06.

**Comment by getcom** [comment] 2019-05-08 17:28
Already installed:

```
Start-Date: 2019-05-07  23:30:04
Commandline: apt dist-upgrade
Install: pve-kernel-4.15.18-14-pve:amd64 (4.15.18-38, automatic)
Upgrade: libpve-access-control:amd64 (5.1-8, 5.1-9), libpve-storage-perl:amd64 (5.0-41, 5.0-42), pve-qemu-kvm:amd64 (2.12.1-3, 3.0.1-2), pve-cluster:amd64 (5.0-36, 5.0-37), qemu-server:amd64 (5.0-50, 5.0-51), pve-kernel-4.15:amd64 (5.4-1, 5.4-2)
End-Date: 2019-05-07  23:30:49

```
I have to test again. Last tests were yesterday before updates.

**Comment by getcom** [comment] 2019-05-08 18:11
Same problem if I want to add a new iSCSI disk to an existing VM:

`error with cfs lock 'storage-iSCSI-ZFS': Unable to find the target id for iscsi-target0 at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 149. at /usr/share/perl5/PVE/API2/Qemu.pm line 1314. (500)
`

**Comment by TheGrandWazoo** [comment] 2019-05-08 19:08
@getcom Could you send a screenshot of the extents in FreeNAS and your Proxmox iSCSI config. Just want to see what we are missing.

**Comment by TheGrandWazoo** [comment] 2019-05-08 19:12
@getcom One thing the target field in Proxmox should be the Target Global Configuration->Base Name + Targets->Target Name (e.g.- iqn.2019-05.com.example.ctl:proxmox)

**Comment by getcom** [comment] 2019-05-08 20:09
@TheGrandWazoo 
That was it. I had in my Proxmox setup only the target name without the base name: (e.g. proxmox, related to your example). 

Now every thing is working.

What I found out in the meanwhile (I added 'ForceCommand logger -p local0.notice "REMOTE SSH: $SSH_ORIGINAL_COMMAND"' to the FreeNAS SSH option in the GUI):
The zvol will be created over a remote SSH session.
First command is to find out if volume is already existing:
`zfs list -o name,volsize,origin,type,refquota -t volume,filesystem -Hr`
Second command is to create the volume:
`zfs create -s -b 4k -V 52428800k pool1/iSCSI/vm-100-disk-0`

The rest is working over iscsiadm commands and this is the reason why the volumes were created, but the Extents and Associated Targets were missing: because of the uncompleted Target entry. 

Thank you for your time.

**Comment by TheGrandWazoo** [comment] 2019-05-09 13:08
Not wasting any time, that's what we are here for. I am trying to remove the need for the ssh and use all API on the FreeNAS side but the ssh stuff is in the ZFSPlugin.pm so this will change a lot of things and could mess up other plugins. I think it is necessary to let the LunCmd do the work for remote control.
I will be branching off the current FreeNAS plugin diffs and files and the head/trunk will be the new development.

Thanks for using the plugin. Glad people have interest in it. Maybe my new backend structure will be used by the Proxmox team.

**Comment by TheGrandWazoo** [comment] 2019-05-09 13:12
I will also see if I can make a Tutorial with some screen shots for people to follow. Might help them out.

**Comment by getcom** [comment] 2019-05-09 21:19
Hi,

If you are building virtual environments you need a cluster and a powerful SAN storage.
You can buy a NetApp, EMC, EVA storage and ESXi if you have budget, if not you are ending at a ZFS storage solution like OmniOS/Napp-IT or FreeNAS and Proxmox. 

I`m using FreeNAS for my Bareos jails which are very fast for network backups of complete infrastructures.
Now I decided to build something new on the storage side: a storage with Infiniband multipath and mirrored Intel Optane ZIL and SLOG PCIe drives and a pool of 8 mirrored vdevs as a ZFS iSCSI target for a Proxmox cluster. 

FreeNAS is a little bit stubborn, because it was tricky to get  the ConnectX-2 QDR cards running in connected mode with a MTU which causes no SCSI kernel errors. Infiniband SDP on FreeNAS is also not working because of missing drivers. The next tests are with ConnectX-3 cards, which are PCIe 3.0 cards, which should reach the 40Gbit/s. This is not possible with PCIe 2.0 (max ~28Gbit/s in my iperf tests). Additionally ConnectX-3 cards are supported by Mellanox to run it on FreeBSD.

The tests from today with ConnectX-2 cards are nevertheless very impressive for the first shot. A live migration of a VM with 50GB disk with 8GB RAM (=58GB to be moved) was finished after 35 seconds with a downtime of 21ms and a migration speed of 1634MB/s. This is not so bad for read and write over the network at the same time.

And this was only possible with your little piece of software.
Thumbs up and thank you!

**Comment by travisghansen** [comment] 2019-05-09 21:30
That. ^ agreed on the cool project.  Not using it yet (hoping it gets upstreamed) but adding another show of appreciation to the mix.  Thanks!

**Comment by TheGrandWazoo** [comment] 2019-08-02 16:49
Closing due to issue was resolved by reapplying the patches/copying the necessary files.

**Closed by TheGrandWazoo** 2019-08-02 16:49 UTC
Labels: Diagnose
