### ISSUE TITLE
problem getting the options to show

### ISSUE THREAD

**Issue by rvyhmeister** [TheGrandWazoo/freenas-proxmox#38] opened 2019-02-09 19:48 UTC
I just tried to install the patch to run FreeNAS as the backend for Proxmox... But the FreeNAS option does not show in the options... what have I missed?

See the output from the patches below... I'm running Proxmox 5.3-9 

Thanks for any feedback!

Ron

```
root@proxmox2:~/freenas-proxmox-master# patch -b /usr/share/pve-manager/js/pvemanagerlib.js < pve-manager/js/pvemanager
lib.js.patch
ch -b /usr/shapatching file /usr/share/pve-manager/js/pvemanagerlib.js
Hunk #1 succeeded at 5916 (offset 22 lines).
Hunk #2 succeeded at 30154 (offset 68 lines).
Hunk #3 succeeded at 30167 (offset 68 lines).
Hunk #4 succeeded at 30204 (offset 68 lines).
Hunk #5 succeeded at 30221 (offset 68 lines).
Hunk #6 succeeded at 30231 (offset 68 lines).
Hunk #7 succeeded at 30246 (offset 68 lines).
Hunk #8 succeeded at 30303 (offset 68 lines).
Hunk #9 succeeded at 30313 (offset 68 lines).
root@proxmox2:~/freenas-proxmox-master# patch -b /usr/share/perl5/PVE/Storage/ZFSPlugin.pm < perl5/PVE/Storage/ZFSPlugi
n.pm.patch
patching file /usr/share/perl5/PVE/Storage/ZFSPlugin.pm
root@proxmox2:~/freenas-proxmox-master# patch -b /usr/share/pve-docs/api-viewer/apidoc.js < pve-docs/api-viewer/apidoc.
js.patch
patching file /usr/share/pve-docs/api-viewer/apidoc.js
Hunk #1 succeeded at 33722 (offset 245 lines).
Hunk #2 succeeded at 33903 (offset 245 lines).
Hunk #3 succeeded at 34116 (offset 245 lines).
root@proxmox2:~/freenas-proxmox-master# apt-get install librest-client-perl
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  librest-client-perl
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 10.3 kB of archives.
After this operation, 32.8 kB of additional disk space will be used.
Get:1 http://ftp.debian.org/debian stretch/main amd64 librest-client-perl all 273-1 [10.3 kB]
Fetched 10.3 kB in 0s (21.7 kB/s)
Selecting previously unselected package librest-client-perl.
(Reading database ... 46931 files and directories currently installed.)
Preparing to unpack .../librest-client-perl_273-1_all.deb ...
Unpacking librest-client-perl (273-1) ...
Setting up librest-client-perl (273-1) ...
Processing triggers for man-db (2.7.6.1-2) ...
root@proxmox2:~/freenas-proxmox-master# cp perl5/PVE/Storage/LunCmd/FreeNAS.pm /usr/share/perl5/PVE/Storage/LunCmd/Free
NAS.pm
root@proxmox2:~/freenas-proxmox-master# systemctl restart pvedaemon
root@proxmox2:~/freenas-proxmox-master# systemctl restart pveproxy
root@proxmox2:~/freenas-proxmox-master# systemctl restart pvestatd
root@proxmox2:~/freenas-proxmox-master#
```

**Comment by TheGrandWazoo** [comment] 2019-02-11 16:06
I will have to upgrade and check with 5.3-9 of Proxmox VE. Looks like something changed in all the backend libs so the patch at 5.3-8 might not give the correct results.

**Comment by TheGrandWazoo** [comment] 2019-02-11 16:41
I just installed patches to a upgrade to Proxmox VE 5.3-9 without previous patches and encountered **no** errors or different offsets then what you provided and the GUI is working as designed.

Here is my output which seems similar to your output (I used a '--verbose' option for more output).

```
fepve01:~/freenas-proxmox# cp perl5/PVE/Storage/LunCmd/FreeNAS.pm /usr/share/perl5/PVE/Storage/LunCmd
fepve01:~/freenas-proxmox# patch --verbose -b /usr/share/pve-manager/js/pvemanagerlib.js < pve-manager/js/pvemanagerlib.js.patch
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|--- pvemanagerlib.js.orig      2019-01-11 04:23:42.000000000 -0500
|+++ pvemanagerlib.js   2019-02-05 07:30:18.168655803 -0500
--------------------------
patching file /usr/share/pve-manager/js/pvemanagerlib.js
Using Plan A...
Hunk #1 succeeded at 5916 (offset 22 lines).
Hunk #2 succeeded at 30154 (offset 68 lines).
Hunk #3 succeeded at 30167 (offset 68 lines).
Hunk #4 succeeded at 30204 (offset 68 lines).
Hunk #5 succeeded at 30221 (offset 68 lines).
Hunk #6 succeeded at 30231 (offset 68 lines).
Hunk #7 succeeded at 30246 (offset 68 lines).
Hunk #8 succeeded at 30303 (offset 68 lines).
Hunk #9 succeeded at 30313 (offset 68 lines).
done
fepve01:~/freenas-proxmox# patch --verbose -b /usr/share/pve-docs/api-viewer/apidoc.js < pve-docs/api-viewer/apidoc.js.patch
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|--- apidoc-5.3-1.js    2018-12-21 12:46:55.459865478 -0500
|+++ apidoc.js  2018-12-06 15:50:21.487987807 -0500
--------------------------
patching file /usr/share/pve-docs/api-viewer/apidoc.js
Using Plan A...
Hunk #1 succeeded at 33722 (offset 245 lines).
Hunk #2 succeeded at 33903 (offset 245 lines).
Hunk #3 succeeded at 34116 (offset 245 lines).
done
fepve01:~/freenas-proxmox# patch --verbose -b /usr/share/perl5/PVE/Storage/ZFSPlugin.pm < perl5/PVE/Storage/ZFSPlugin.pm.patch
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|--- ZFSPlugin-5.0-34.pm        2018-12-21 12:52:21.764194866 -0500
|+++ ZFSPlugin.pm       2018-12-21 12:53:08.663665081 -0500
--------------------------
patching file /usr/share/perl5/PVE/Storage/ZFSPlugin.pm
Using Plan A...
Hunk #1 succeeded at 10.
Hunk #2 succeeded at 27.
Hunk #3 succeeded at 42.
Hunk #4 succeeded at 66.
Hunk #5 succeeded at 166.
Hunk #6 succeeded at 193.
Hunk #7 succeeded at 238.
Hunk #8 succeeded at 274.
done
fepve01:~/freenas-proxmox# apt-get install libreset-client-perl
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libreset-client-perl
fepve01:~/freenas-proxmox# apt-get install librest-client-perl
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  librest-client-perl
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 10.3 kB of archives.
After this operation, 32.8 kB of additional disk space will be used.
Get:1 http://ftp.us.debian.org/debian stretch/main amd64 librest-client-perl all 273-1 [10.3 kB]
Fetched 10.3 kB in 0s (111 kB/s)
Selecting previously unselected package librest-client-perl.
(Reading database ... 133432 files and directories currently installed.)
Preparing to unpack .../librest-client-perl_273-1_all.deb ...
Unpacking librest-client-perl (273-1) ...
Setting up librest-client-perl (273-1) ...
Processing triggers for man-db (2.7.6.1-2) ...
fepve01:~/freenas-proxmox# pvedaemon restart
fepve01:~/freenas-proxmox# pveproxy restart
fepve01:~/freenas-proxmox# pvestatd restart
fepve01:~/freenas-proxmox# pveversion -v
proxmox-ve: 5.3-1 (running kernel: 4.15.18-10-pve)
pve-manager: 5.3-9 (running version: 5.3-9/ba817b29)
pve-kernel-4.15: 5.3-2
pve-kernel-4.13: 5.2-2
pve-kernel-4.15.18-11-pve: 4.15.18-33
pve-kernel-4.15.18-10-pve: 4.15.18-32
pve-kernel-4.15.18-8-pve: 4.15.18-28
pve-kernel-4.15.18-3-pve: 4.15.18-22
pve-kernel-4.15.18-1-pve: 4.15.18-19
pve-kernel-4.13.16-4-pve: 4.13.16-51
pve-kernel-4.13.16-2-pve: 4.13.16-48
pve-kernel-4.13.13-6-pve: 4.13.13-42
pve-kernel-4.13.13-5-pve: 4.13.13-38
pve-kernel-4.4.98-5-pve: 4.4.98-105
pve-kernel-4.4.83-1-pve: 4.4.83-96
pve-kernel-4.4.59-1-pve: 4.4.59-87
pve-kernel-4.4.40-1-pve: 4.4.40-82
pve-kernel-4.4.35-2-pve: 4.4.35-79
corosync: 2.4.4-pve1
criu: 2.11.1-1~bpo90
glusterfs-client: 3.8.8-1
ksm-control-daemon: 1.2-2
libjs-extjs: 6.0.1-2
libpve-access-control: 5.1-3
libpve-apiclient-perl: 2.0-5
libpve-common-perl: 5.0-45
libpve-guest-common-perl: 2.0-20
libpve-http-server-perl: 2.0-11
libpve-storage-perl: 5.0-37
libqb0: 1.0.3-1~bpo9
lvm2: 2.02.168-pve6
lxc-pve: 3.1.0-2
lxcfs: 3.0.2-2
novnc-pve: 1.0.0-2
proxmox-widget-toolkit: 1.0-22
pve-cluster: 5.0-33
pve-container: 2.0-34
pve-docs: 5.3-2
pve-edk2-firmware: 1.20181023-1
pve-firewall: 3.0-17
pve-firmware: 2.0-6
pve-ha-manager: 2.0-6
pve-i18n: 1.0-9
pve-libspice-server1: 0.14.1-2
pve-qemu-kvm: 2.12.1-1
pve-xtermjs: 3.10.1-1
qemu-server: 5.0-46
smartmontools: 6.5+svn4324-1
spiceterm: 3.0-5
vncterm: 1.5-3
zfsutils-linux: 0.7.12-pve1~bpo1
fepve01:~/freenas-proxmox#
```

You sometimes need to refresh your browser so the new Javascript code is downloaded to execute correctly on your browser.

![image](https://user-images.githubusercontent.com/1273753/52578101-86983100-2df1-11e9-93cc-594d121cd2b4.png)

**Comment by rvyhmeister** [comment] 2019-02-11 17:15
Thanks! I wound up having to switch to another browser entirely... Now for the rest of the configuration...

**Comment by TheGrandWazoo** [comment] 2019-02-12 20:21
Closing. Client stated it is working as designed.

**Closed by TheGrandWazoo** 2019-02-12 20:21 UTC
Labels: invalid
